### ISSUE TITLE
Todo list to catch up

### ISSUE THREAD

**Issue by jourdain** [Kitware/hpccloud-client#1]
- [ ] Site pages
    - [x] login
    - [x] register
    - [ ] forget password
    - [ ] landing page (the nice one...)
- [ ] Simput
  - [x] UI
  - [ ] file generation on backend
- [ ] Job submission
  - [x] UI
  - [x] Backend calls
- [x] Job monitoring
  - [x] UI
  - [x] Backend calls
- [ ] Add tools
  - [ ] Visualizer?
  - [x] PV-Lite
  - [ ] PV-Flow
- [x] CRUD pages
  - [x] Project
    - [x] create
    - [x] edit
    - [x] delete
  - [x] Simulation
    - [x] create
    - [x] edit
    - [x] delete
- [ ] Custom workflow add-on
    - [ ] project
    - [ ] simulation
    - [ ] job submission
- [ ] Configuration pages
  - [ ] Traditional cluster 
    - [ ] create
    - [ ] edit
    - [ ] delete
  - [ ] EC2
    - [ ] create
    - [ ] edit
    - [ ] delete
  - [ ] ?
- [ ] Worflows
  - [ ] Parflow Conus
  - [ ] Parflow Washita
  - [x] Visualizer
  - [ ] PyFr
  - [ ] OpenFOAM ?
